#!/usr/bin/env bash

export PENJAR_NITRATE_SHARED_KEY=super-secret-nitrate-api-key
export PENJAR_EXPORTER_SHARED_KEY=super-secret-exporter-api-key
export PENJAR_SECRET_KEY=super-secret-devenv-key

# DEPRECATED: only used for subscriptions
export PENJAR_MANAGEMENT_API_KEY=super-secret-management-api-key

export PENJAR_HOST=devenv
export PENJAR_PUBLIC_URI=https://localhost:3449

export PENJAR_FLAGS="\
       $PENJAR_FLAGS \
       enable-login-with-password
       disable-login-with-ldap \
       disable-login-with-oidc \
       disable-login-with-google \
       disable-login-with-github \
       disable-login-with-gitlab \
       disable-telemetry \
       enable-backend-worker \
       enable-backend-asserts \
       disable-feature-fdata-pointer-map \
       enable-feature-fdata-objects-map \
       enable-audit-log \
       enable-transit-readable-response \
       enable-demo-users \
       enable-user-feedback \
       disable-secure-session-cookies \
       enable-smtp \
       enable-prepl-server \
       enable-urepl-server \
       enable-rpc-climit \
       enable-rpc-rlimit \
       enable-quotes \
       enable-soft-rpc-rlimit \
       enable-auto-file-snapshot \
       enable-webhooks \
       enable-access-tokens \
       disable-tiered-file-data-storage \
       enable-file-validation \
       enable-file-schema-validation \
       enable-redis-cache \
       enable-subscriptions";

# Default deletion delay for devenv
export PENJAR_DELETION_DELAY="24h"

# Setup default upload media file size to 100MiB
export PENJAR_MEDIA_MAX_FILE_SIZE=104857600

# Setup default multipart upload size to 300MiB
export PENJAR_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=314572800

export PENJAR_USER_FEEDBACK_DESTINATION="support@example.com"

export AWS_ACCESS_KEY_ID=penjar-devenv
export AWS_SECRET_ACCESS_KEY=penjar-devenv
export PENJAR_OBJECTS_STORAGE_BACKEND=s3
export PENJAR_OBJECTS_STORAGE_S3_ENDPOINT=http://minio:9000
export PENJAR_OBJECTS_STORAGE_S3_BUCKET=penjar

export PENJAR_NITRATE_BACKEND_URI=http://localhost:3000/control-center

export JAVA_OPTS="\
       -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
       -Djdk.attach.allowAttachSelf \
       -Dlog4j2.configurationFile=log4j2-devenv.xml \
       -Djdk.tracePinnedThreads=full \
       -Dim4java.useV7=true \
       -XX:+UnlockExperimentalVMOptions \
       -XX:+UseShenandoahGC \
       -XX:+UseCompactObjectHeaders \
       -XX:ShenandoahGCMode=generational \
       -XX:-OmitStackTraceInFastThrow  \
       --sun-misc-unsafe-memory-access=allow \
       --enable-preview \
       --enable-native-access=ALL-UNNAMED";

function setup_minio() {
    # Initialize MINIO config
    mc alias set penjar-s3/ http://minio:9000 minioadmin minioadmin -q
    mc admin user add penjar-s3 penjar-devenv penjar-devenv -q
    mc admin user info penjar-s3 penjar-devenv |grep -F -q "readwrite"
    if [ "$?" = "1" ]; then
        mc admin policy attach penjar-s3 readwrite --user=penjar-devenv -q
    fi
    mc mb penjar-s3/penjar -p -q
}


