## Common flags:
# demo-users
# email-verification
# log-emails
# log-invitation-tokens
# login-with-github
# login-with-gitlab
# login-with-google
# login-with-ldap
# login-with-oidc
# login-with-password
# prepl-server
# registration
# secure-session-cookies
# smtp
# smtp-debug
# telemetry
# webhooks
##
## You can read more about all available flags and other
## environment variables here:
## https://help.penjar.app/technical-guide/configuration/#penjar-configuration
#
# WARNING: if you're exposing Penjar to the internet, you should remove the flags
# 'disable-secure-session-cookies' and 'disable-email-verification'
x-flags: &penjar-flags
  PENJAR_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies

x-uri: &penjar-public-uri
  PENJAR_PUBLIC_URI: http://localhost:9001

x-body-size: &penjar-http-body-size
  # Max body size
  PENJAR_HTTP_SERVER_MAX_BODY_SIZE: 367001600
  # Deprecation warning: this variable is deprecated. Use PENJAR_HTTP_SERVER_MAX_BODY (defaults to 367001600)
  PENJAR_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE: 367001600

## Penjar SECRET KEY. It serves as a master key from which other keys for subsystems
## (eg http sessions, or invitations) are derived.
##
## We recommend to use a trully randomly generated
## 512 bits base64 encoded string here. You can generate one with:
##
## python3 -c "import secrets; print(secrets.token_urlsafe(64))"
x-secret-key: &penjar-secret-key
  PENJAR_SECRET_KEY: change-this-insecure-key

networks:
  penjar:

volumes:
  penjar_postgres_v15:
  penjar_assets:
  # penjar_traefik:

services:
  ## Traefik service declaration example. Consider using it if you are going to expose
  ## penjar to the internet, or a different host than `localhost`.

  # traefik:
  #   image: traefik:v3.3
  #   networks:
  #     - penjar
  #   command:
  #     - "--api.insecure=true"
  #     - "--entryPoints.web.address=:80"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entryPoints.websecure.address=:443"
  #     - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  #     - "--certificatesresolvers.letsencrypt.acme.email=<EMAIL_ADDRESS>"
  #     - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
  #   volumes:
  #     - "penjar_traefik:/traefik"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - "80:80"
  #     - "443:443"

  penjar-frontend:
    image: "penjarapp/frontend:${PENJAR_VERSION:-latest}"
    restart: always
    ports:
      - 9001:8080

    volumes:
      - penjar_assets:/opt/data/assets

    depends_on:
      - penjar-backend
      - penjar-exporter

    networks:
      - penjar

    # labels:
      # - "traefik.enable=true"

      # ## HTTPS: example of labels for the case where penjar will be exposed to the
      # ## internet with HTTPS using traefik.

      # - "traefik.http.routers.penjar-https.rule=Host(`<DOMAIN_NAME>`)"
      # - "traefik.http.routers.penjar-https.entrypoints=websecure"
      # - "traefik.http.routers.penjar-https.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.penjar-https.tls=true"

    environment:
      << : [*penjar-flags, *penjar-http-body-size]

  penjar-backend:
    image: "penjarapp/backend:${PENJAR_VERSION:-latest}"
    restart: always

    volumes:
      - penjar_assets:/opt/data/assets

    depends_on:
      penjar-postgres:
        condition: service_healthy
      penjar-valkey:
        condition: service_healthy

    networks:
      - penjar

    ## Configuration envronment variables for the backend container.

    environment:
      << : [*penjar-flags, *penjar-public-uri, *penjar-http-body-size, *penjar-secret-key]

      ## Database connection parameters. Don't touch them unless you are using custom
      ## postgresql connection parameters.

      PENJAR_DATABASE_URI: postgresql://penjar-postgres/penjar
      PENJAR_DATABASE_USERNAME: penjar
      PENJAR_DATABASE_PASSWORD: penjar

      ## Valkey (or previously redis) is used for the websockets notifications. Don't touch
      ## unless the valkey container has different parameters or different name.

      PENJAR_REDIS_URI: redis://penjar-valkey/0

      ## Default configuration for assets storage: using filesystem based with all files
      ## stored in a docker volume.

      PENJAR_OBJECTS_STORAGE_BACKEND: fs
      PENJAR_OBJECTS_STORAGE_FS_DIRECTORY: /opt/data/assets

      ## Also can be configured to to use a S3 compatible storage.

      # AWS_ACCESS_KEY_ID: <KEY_ID>
      # AWS_SECRET_ACCESS_KEY: <ACCESS_KEY>
      # PENJAR_OBJECTS_STORAGE_BACKEND: s3
      # PENJAR_OBJECTS_STORAGE_S3_ENDPOINT: <ENDPOINT>
      # PENJAR_OBJECTS_STORAGE_S3_BUCKET: <BUKET_NAME>

      ## Telemetry. When enabled, a periodical process will send anonymous data about this
      ## instance. Telemetry data will enable us to learn how the application is used,
      ## based on real scenarios. If you want to help us, please leave it enabled. You can
      ## audit what data we send with the code available on github.

      PENJAR_TELEMETRY_ENABLED: true
      PENJAR_TELEMETRY_REFERER: compose

      ## Example SMTP/Email configuration. By default, emails are sent to the mailcatch
      ## service, but for production usage it is recommended to setup a real SMTP
      ## provider. Emails are used to confirm user registrations & invitations. Look below
      ## how the mailcatch service is configured.

      PENJAR_SMTP_DEFAULT_FROM: no-reply@example.com
      PENJAR_SMTP_DEFAULT_REPLY_TO: no-reply@example.com
      PENJAR_SMTP_HOST: penjar-mailcatch
      PENJAR_SMTP_PORT: 1025
      PENJAR_SMTP_USERNAME:
      PENJAR_SMTP_PASSWORD:
      PENJAR_SMTP_TLS: false
      PENJAR_SMTP_SSL: false

  penjar-exporter:
    image: "penjarapp/exporter:${PENJAR_VERSION:-latest}"
    restart: always

    depends_on:
      penjar-valkey:
        condition: service_healthy

    networks:
      - penjar

    environment:
      << : [*penjar-secret-key]
      # Don't touch it; this uses an internal docker network to
      # communicate with the frontend.
      PENJAR_PUBLIC_URI: http://penjar-frontend:8080

      ## Valkey (or previously Redis) is used for the websockets notifications.
      PENJAR_REDIS_URI: redis://penjar-valkey/0

  penjar-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penjar"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s

    volumes:
      - penjar_postgres_v15:/var/lib/postgresql/data

    networks:
      - penjar

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penjar
      - POSTGRES_USER=penjar
      - POSTGRES_PASSWORD=penjar

  penjar-valkey:
    image: valkey/valkey:8.1
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s

    networks:
      - penjar

    environment:
      # You can increase the max memory size if you have sufficient resources,
      # although this should not be necessary.
      - VALKEY_EXTRA_FLAGS=--maxmemory 128mb --maxmemory-policy volatile-lfu

  ## A mailcatch service, used as temporal SMTP server. You can access via HTTP to the
  ## port 1080 for read all emails the penjar platform has sent. Should be only used as a
  ## temporal solution while no real SMTP provider is configured.

  penjar-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penjar
